### ISSUE TITLE
./flash_device.sh: 3: ./flash_device.sh: 1: not found

### ISSUE THREAD

**Issue by pshashipreetham** [krenzlin/rust-stm32f466-blinky#1]
When I Ran the command "**sudo ./flash_device.sh target/thumbv7em-none-eabihf/debug/blinky**"

I got the following error :

./flash_device.sh: 3: ./flash_device.sh: 1: not found
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v30 API v2 SWIM v19 VID 0x0483 PID 0x374B
Info : using stlink api v2
Info : Target voltage: 3.253193
Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
adapter speed: 1800 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x08001328 msp: 0x20020000
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
Info : Unable to match requested speed 8000 kHz, using 4000 kHz
adapter speed: 4000 kHz
** Programming Started **
auto erase enabled
Info : device id = 0x10006421
Info : flash size = 512kbytes
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x20000046 msp: 0x20020000
wrote 16384 bytes from file target/thumbv7em-none-eabihf/debug/blinky in 0.558255s (28.661 KiB/s)
** Programming Finished **
** Verify Started **
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x2000002e msp: 0x20020000
verified 6068 bytes in 0.041080s (144.250 KiB/s)
** Verified OK **
** Resetting Target **
Info : Unable to match requested speed 2000 kHz, using 1800 kHz

**Comment by krenzlin** [comment]
Thanks for your issue.

The name "blinky" is a bit misleading. You have to press one of the buttons to light the LED. 
Did that work?

Actually the output looks okay. (c.f. `** Programming Finished **` and `** Verified OK **`)

The only error is in the first line `./flash_device.sh: 3: ./flash_device.sh: 1: not found` which I cannot parse. Could you post the output using the markdown code block?

**Comment by pshashipreetham** [comment]
According to me, **flash_device.sh** is not executing, it's showing **not found** while executing the final Command
![Screenshot from 2020-07-08 22-13-52](https://user-images.githubusercontent.com/42883804/86946722-6e544f00-c168-11ea-9a18-484e07ccfa74.png)

**Comment by krenzlin** [comment]
Could you please try `sudo bash flash_device.sh` instead?

**Comment by pshashipreetham** [comment]
I am getting Following **Output**t...
![image](https://user-images.githubusercontent.com/42883804/86997999-100d8780-c1cd-11ea-8c67-c62c9070a43f.png)

**Comment by krenzlin** [comment]
Sorry the complete command was meant to be 
`sudo bash flash_device.sh target/thumbv7em-none-eabihf/debug/blinky`.

Did pressing the user button work to light up the LED?

**Comment by pshashipreetham** [comment]
Yes That issue has gone now, Thanks !

But the main issue is still remaining that is  **Resetting target** shutdown command invoked

![image](https://user-images.githubusercontent.com/42883804/87027769-47932880-c1fb-11ea-9e79-e152c87601c7.png)

**Comment by pshashipreetham** [comment]
Code is uploading Now 
what I Did is
----> In  **terminal 1** I used following commands: 
```
cd rust-stm32f446-blinky
arm-none-eabi-gdb target/thumbv7em-none-eabihf/release/blinky
```
----> In terminal 2 I have opened openocd connection by follwoing Command
```
cd rust-stm32f446-blinky
openocd -f openocd.cfg
```
---->In terminal 1 again I used following commands
`target remote: 3333`
after this to flash the code, I have used following command
`load`
![image](https://user-images.githubusercontent.com/42883804/87116613-d784b100-c293-11ea-9889-ca45c0e712cf.png)
that's it the code got flashed in to **NucleoF446RE**

Thanks @krenzlin for help, Thanks a Lot !
